services:
  app: &base
    build: .
    command: composer ci
    environment:
      DB_USER: root
      DB_PASSWORD: somePassword
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: testdb
    volumes:
      - ssh-keys:/root/.ssh:ro
    depends_on:
      - mariadb
      - toxiproxy
      - sshproxy

  dev:
    <<: *base
    volumes:
      - .:/code
      - ssh-keys:/root/.ssh:ro

  wait:
    image: waisbrot/wait
    depends_on:
      - mariadb
      - sshproxy
    environment:
      - TARGETS=mariadb:3306,sshproxy:22
      - TIMEOUT=60

  toxiproxy:
    image: shopify/toxiproxy
    depends_on:
      - mariadb

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - mariadb

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: somePassword

volumes:
  ssh-keys:
